### ISSUE TITLE
Incorrect align "Add cover" title on pages

### ISSUE THREAD

**Issue by MPaandeey** [EliWimmer/notion-style-tweaks#13]
Smaller Page Titles tweaker is incorrectly align ```Add cover``` options
### Now
![Before](https://user-images.githubusercontent.com/35831198/169638847-e7294396-07ff-47c7-9cd6-612668a08d74.jpeg)

### After
![After](https://user-images.githubusercontent.com/35831198/169638896-fcf81cdb-8b30-475f-86cf-9d3c78801d90.jpeg)

**Code i got from internet**

``` css
.notion-record-icon[style*="margin-bottom: 0px; align-self: flex-start;"] {
top: 66px;
height: 0px !important;
width: 38px !important;
margin-top: 0px !important;
}
.notion-record-icon[style*="margin-bottom: 0px; align-self: flex-start;"] * {
height: 50px !important;
width: 50px !important;
display: block;
}
.notion-page-block > [data-content-editable-leaf="true"] {
margin-left: 52px;
}
````
Note : The icon and heading now look very small so make it little bigger,size provided in code
